core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import register_view, login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/register/', register_view, name='register'),
    path('accounts/login/', login_view, name='login'),
    path('accounts/logout/', logout_view, name='logout'),

    path('', include('products.urls'))
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('products/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/detail/', views.ProductDetailView.as_view(), name='product_detail'),
    #path('products/<int:pk>/update/', ..., name='product_update'),
    #path('products/<int:pk>/delete/', ..., name='product_delete'),
]

company/models.py
from django.contrib.auth.models import User
from django.db import models


class Company(models.Model):
    name = models.CharField(max_length=150)
    code = models.CharField(max_length=4, blank=True, null=True)

    def __str__(self):
        return self.name


class CompanyUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='company_user')
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='users')
    role = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return f'{self.user.username} - {self.company.name}'

products/models.py
from django.contrib.auth.models import User
from django.db import models


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    value = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title
    

products/forms.py
from django import forms
from . import models


class ProductForm(forms.ModelForm):

    class Meta:
        model = models.Product
        fields = ['title', 'value']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'value': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'title': 'Produto',
            'value': 'Valor',
        }

company/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout


def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()

    return render(request, 'registration/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('product_list')

    return render(request, 'registration/login.html')


def logout_view(request):
    logout(request)
    return redirect('login')

products/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from . import models, forms, permissions


class ProductListView(LoginRequiredMixin, ListView):
    model = models.Product
    template_name = 'product_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        return models.Product.objects.filter(
            user=self.request.user
        )


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = models.Product
    template_name = 'product_create.html'
    form_class = forms.ProductForm
    success_url = reverse_lazy('product_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    

class ProductDetailView(LoginRequiredMixin, permissions.UserIsOwnerMixin, DetailView):
    model = models.Product
    template_name = 'product_detail.html'


class ProductUpdateView(LoginRequiredMixin, permissions.UserIsOwnerMixin, UpdateView):
    pass


class ProductDeleteView(LoginRequiredMixin, permissions.UserIsOwnerMixin, DeleteView):
    pass

core/templates/base.html
<!DOCTYPE html>
<html lang="pt-br" data-bs-theme="dark">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>

<body>
  {% include 'components/_header.html' %}

  <div class="container-fluid">
    {% if user.is_authenticated %}
    {% endif %}

      <div class="col py-3">

        <div class="container mt-4">
          <main>
            {% block content %}
            {% endblock %}
          </main>
        </div>

      </div>
    </div>
  </div>
  {% include 'components/_footer.html' %}
</body>

</html>

core/templates/components/_footer.html
<footer class="footer mt-auto py-3 text-center">
  <div class="container">
    <span class="text-muted">© 2024 SGE</span>
  </div>
</footer>

core/templates/components/_header.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
  </div>
</nav>

core/templates/components/_pagination.html
{% if page_obj.has_other_pages %}
  <nav>
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">
            Primeira
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Anterior
          </a>
        </li>
      {% endif %}

      {% for page_number in page_obj.paginator.page_range %}
        {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
          {% if page_obj.number == page_number %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Próxima
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Última
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

core/templates/components/_sidebar.html
<div class="row flex-nowrap">
  <div class="col-auto col-md-0 col-xl-0 px-0 bg-dark">
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white">
      <button class="btn btn-dark d-block d-sm-none mb-3" type="button" data-bs-toggle="collapse"
        data-bs-target="#menuCollapse" aria-expanded="false" aria-controls="menuCollapse">
        <i class="bi bi-list fs-4"></i>
      </button>
      <div class="collapse d-sm-block" id="menuCollapse">
        <ul class="nav flex-column align-items-start" id="menu">
          <li>
            <a href="#" class="nav-link px-0 align-middle">
              <i class="bi bi-speedometer2 fs-4"></i>
              <span class="ms-1">Dashboard</span>
            </a>
          </li>
          {% if perms.suppliers.view_supplier %}
            <li>
              <a href="#" class="nav-link px-0 align-middle">
                <i class="bi bi-truck fs-4"></i>
                <span class="ms-1">Fornecedores</span>
              </a>
            </li>
          {% endif %}
          {% if perms.brands.view_brand %}
            <li>
              <a href="#" class="nav-link px-0 align-middle">
                <i class="bi bi-shop fs-4"></i>
                <span class="ms-1">Marcas</span>
              </a>
            </li>
          {% endif %}
          {% if perms.categories.view_category %}
            <li>
              <a href="#" class="nav-link px-0 align-middle">
                <i class="bi bi-tags fs-4"></i>
                <span class="ms-1">Categorias</span>
              </a>
            </li>
          {% endif %}
          {% if perms.products.view_product %}
            <li>
              <a href="#" class="nav-link px-0 align-middle">
                <i class="bi bi-box-seam fs-4"></i>
                <span class="ms-1">Produtos</span>
              </a>
            </li>
          {% endif %}
          {% if perms.inflows.view_inflow %}
            <li>
              <a href="#" class="nav-link px-0 align-middle">
                <i class="bi bi-arrow-down-left-square fs-4"></i>
                <span class="ms-1">Entradas</span>
              </a>
            </li>
          {% endif %}
          {% if perms.outflows.view_outflow %}
            <li>
              <a href="#" class="nav-link px-0 align-middle">
                <i class="bi bi-arrow-up-right-square fs-4"></i>
                <span class="ms-1">Saídas</span>
              </a>
            </li>
          {% endif %}
          <li class="nav-item">
            {% if user.is_authenticated %}
            <form action="#" method="post" id="logout-form" class="nav-link px-0 align-middle">
              {% csrf_token %}
              <button type="submit" class="btn btn-link text-decoration-none text-reset nav-link px-0 align-middle">
                <i class="bi bi-box-arrow-right fs-4 align-middle"></i>
                <span class="ms-1 align-middle">Sair</span>
              </button>
            </form>
            {% endif %}
          </li>
        </ul>
      </div>
      <hr>
    </div>
  </div>

products/templates/product_create.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <h3 class="display-4">Cadastrar Produto</h3>

    <div class="card">
      <div class="card-body">
        <form method="post" class="form">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
      </div>
    </div>
    <a href="{% url 'product_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar</a>
  </div>
{% endblock %}

products/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <h3 class="display-4">Detalhes do Produto</h3>

    <div class="card">
      <div class="card-body">
        <h3 class="card-title">{{ product.title }}</h3>
        <p class="card-text">{{ product.value }}</p>
      </div>
    </div>

    <a href="{% url 'product_list' %}" class="btn btn-secondary mt-3">Voltar</a>
  </div>
{% endblock %}

products/templates/product_list.html
{% extends 'base.html' %}

{% block title %}
SGE
{% endblock %}

{% block content %}

<div class="row mb-3">
  <div class="col-md-6">
    <form method="get" action="#">
      <div class="input-group">
        <input type="text" class="form-control" name="name" placeholder="Nome" value="{{ request.GET.name }}">
        <button type="submit" class="btn btn-primary">
          <i class="bi bi-search"></i>
        </button>
      </div>
    </form>
  </div>
  {% if perms.brands.add_brand %}
  <div class="col-md-6">
    <a href="{% url 'product_create' %}" class="btn btn-success float-end">
      <i class="bi bi-plus"></i> Produto
    </a>
  </div>
  {% endif %}
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Valor</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for product in products %}
      <tr>
        <td>
          <a href="#" class="text-primary fw-semibold">
            {{ product.id }}
          </a>
        </td>
        <td>{{ product.title }}</td>
        <td>{{ product.value }}</td>
        <td>
          <a href="{% url 'product_detail' product.id %}" class="btn btn-info btn-sm">
            <i class="bi bi-eye"></i>
          </a>

          {% if perms.brands.change_brand %}
          <a href="#" class="btn btn-warning btn-sm">
            <i class="bi bi-pencil"></i>
          </a>
          {% endif %}

          {% if perms.brands.delete_brand %}
          <a href="#" class="btn btn-danger btn-sm btn-delete">
            <i class="bi bi-trash"></i>
          </a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% include 'components/_pagination.html' %}

{% endblock %}